create table if not exists public.pizza_ballots (
  id bigint generated by default as identity primary key,
  voter_name text not null check (char_length(voter_name) between 1 and 80),
  votes jsonb not null check (jsonb_typeof(votes) = 'object'),
  created_at timestamptz not null default now()
);

alter table public.pizza_ballots enable row level security;

grant select, insert on table public.pizza_ballots to anon, authenticated;
grant usage, select on sequence public.pizza_ballots_id_seq to anon, authenticated;

create policy "Anyone can read pizza ballots"
on public.pizza_ballots
for select
to anon, authenticated
using (true);

create policy "Anyone can submit a pizza ballot"
on public.pizza_ballots
for insert
to anon, authenticated
with check (true);

-- Needed for the simple Postgres Changes realtime subscription used by the app.
alter publication supabase_realtime add table public.pizza_ballots;
